### ISSUE TITLE
Question: Is this approach feasible for "3d"?

### ISSUE THREAD

**Issue by janis-me** [martinRenou/threejs-water#2]
Hey! Thanks a lot for sharing this.

I hope this question is not too stupid: Would it be possible to, instead of using a Plane geometry for this, to use for example a cube? My scenario would be to use the shaders etc but use a pre-defined surface mesh for the "target". Do you think this is possible?

Best regards!

**Comment by martinRenou** [comment]
Hey :)

This implementation will only work with very simple geometries. Though I pushed another implementation here: https://github.com/martinRenou/threejs-caustics with an explanation of how it works: https://medium.com/@martinRenou/real-time-rendering-of-water-caustics-59cda1d74aa

This other implementation supports any kind of mesh

**Comment by janis-me** [comment]
Thank you for the quick answer! This other repo helps me a lot, thank you!
